### ISSUE TITLE
index out of range possible

### ISSUE THREAD

**Issue by rickb777** [simpleforce/simpleforce#13]
It's possible to get a panic because there's an error at line 86
https://github.com/simpleforce/simpleforce/blob/2062cbbdbb8971713fe9d151510bdef9c0837675/sobject.go#L86

If the id slice is empty but not nil, there will be a panic on line 87.

So line 86 should read

```go
    if len(id) > 0 {
```

**Comment by cuiwc** [comment]
Nice catch, thanks, @rickb777 !
